//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verko_Shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpPoints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickUpPoints()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PickUpPointID { get; set; }
        public int PickUpPointIndex { get; set; }
        public string PickUpPointCity { get; set; }
        public string PickUpPointStreet { get; set; }
        public Nullable<int> PickUpPointHouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
